#!/bin/bash
#
# Author: Cyril GENISSON
# Created: 08/10/2023
# Updated: 08/10/2023
#
# Description: créé un jeu de clefs ssh et stock les clefs dans le répertoire ~/.ssh
#

# Activation du mode debug, à commenter quand le script est opérationnel
#set -ux

#################################################
#		Variables utilisateur		#
#################################################
ALGO=ed25519
COMMENT=
NAME=$1
FILE="$HOME/.ssh/$NAME"
PASSWD=
REPORT="$HOME/.ssh/report_$NAME"

if [ -z $NAME ] || [ -z $PASSWORD ] || [ -z $COMMENT ] ; then
	echo "Il faut modifier les variables dans le script!"
	echo "Utilisation: $0 KEY_NAME"
	exit 1
else if [ -e $FILE ] ; then
	echo "Ce nom de clef \"$NAME\" existe déjà!"
	echo "Fin du programme sans génération de clef."
	exit 1
	fi
fi

ssh-keygen -t $ALGO -C $COMMENT -N $PASSWD -f $FILE | tee  $REPORT
